joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 111 # Up to 333 HZ

joint_ff_controller:
  type: joint_group_ff_controllers/JointGroupEffortFFController
  joints:
  - joint_0
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  - joint_7
  - joint_8
  - joint_9
  - joint_10
  - joint_11
  - joint_12
  - joint_13
  - joint_14
  - joint_15
  joint_0 : { kp: 0, kd: 0, kp_safe: 0.1, kd_safe: 0.1 }
  joint_1 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_2 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_3 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_4 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_5 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_6 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_7 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_8 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_9 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_10 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_11 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_12 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_13 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_14 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }
  joint_15 : { kp: 0, kd: 0, kp_safe: 0, kd_safe: 0 }