joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 111 # Up to 333 HZ

joint_ff_controller:
  type: joint_group_ff_controllers/JointGroupEffortFFController
  joints:
  - joint_00
  - joint_01
  - joint_02
  - joint_03
  - joint_04
  - joint_05
  - joint_06
  - joint_07
  - joint_08
  - joint_09
  - joint_10
  - joint_11
  - joint_12
  - joint_13
  - joint_14
  - joint_15
  joint_00 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_01 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_02 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_03 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_04 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_05 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_06 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_07 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_08 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_09 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_10 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_11 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_12 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_13 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_14 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }
  joint_15 : { kp: 0, kd: 0, kp_safe: 5, kd_safe: 0.2 }